# Generated by Django 5.1.4 on 2025-01-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0012_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("category", "-created")},
        ),
    ]
